# Generated by Django 3.1.1 on 2020-09-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_conf_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='conf_path',
            name='file',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
